### ISSUE TITLE
Error instantiating of EntityIdPathConverter with Quarkus (ver.: 1.5.2.Final)

### ISSUE THREAD

**Issue by AlexHamburg** [fuinorg/ddd-4-java#2]
It looks like EntityIdPathConverter should have default constructor without arguments:
**java.lang.NoSuchMethodException: org.fuin.ddd4j.ddd.EntityIdPathConverter.<init>()**

Complete error message:
```
Caused by: java.lang.IllegalStateException: Cannot instantiate JSON-B component: class org.fuin.ddd4j.ddd.EntityIdPathConverter
	at io.quarkus.jsonb.QuarkusJsonbComponentInstanceCreator.fallbackCreate(QuarkusJsonbComponentInstanceCreator.java:56) ~[quarkus-jsonb-1.5.2.Final.jar!/:1.5.2.Final]
	at io.quarkus.jsonb.QuarkusJsonbComponentInstanceCreator.lambda$getOrCreateComponent$0(QuarkusJsonbComponentInstanceCreator.java:48) ~[quarkus-jsonb-1.5.2.Final.jar!/:1.5.2.Final]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_252]
	at io.quarkus.jsonb.QuarkusJsonbComponentInstanceCreator.getOrCreateComponent(QuarkusJsonbComponentInstanceCreator.java:37) ~[quarkus-jsonb-1.5.2.Final.jar!/:1.5.2.Final]
	at org.eclipse.yasson.internal.ComponentMatcher.introspectAdapterBinding(ComponentMatcher.java:264) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:240) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBinding(AnnotationIntrospector.java:218) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.model.PropertyModel.introspectCustomization(PropertyModel.java:239) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:137) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:71) ~[yasson-1.0.7.jar!/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_252]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628) ~[na:1.8.0_252]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_252]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_252]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_252]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_252]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_252]
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:72) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:97) ~[yasson-1.0.7.jar!/:na]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_252]
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:81) ~[yasson-1.0.7.jar!/:na]
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:60) ~[yasson-1.0.7.jar!/:na]
	... 30 common frames omitted
Caused by: java.lang.InstantiationException: org.fuin.ddd4j.ddd.EntityIdPathConverter
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_252]
	at io.quarkus.jsonb.QuarkusJsonbComponentInstanceCreator.fallbackCreate(QuarkusJsonbComponentInstanceCreator.java:54) ~[quarkus-jsonb-1.5.2.Final.jar!/:1.5.2.Final]
	... 51 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.fuin.ddd4j.ddd.EntityIdPathConverter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_252]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_252]
	... 52 common frames omitted
```

**Comment by michael-schnell** [comment]
Did you try to use a CDI producer for this that creates the Jsonb object?

Here is an example:
https://github.com/fuinorg/ddd-cqrs-4-java-example/blob/master/quarkus/shared/src/main/java/org/fuin/cqrs4j/example/quarkus/shared/JsonbFactory.java

It looks like the Quarkus default mechanism is used to find the JSON-B converter classes. If you create the object yourself, it should also work as described here: https://quarkus.io/guides/rest-json#json-b

**Comment by AlexHamburg** [comment]
Thx, sorry, I forgot about mandatory custom JsonbFactory.
